# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "cdk"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "logic/chargableCars"
    schedule:
      interval: "monthly"
