name: GreenMo Stalker deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'cdk/**'
      - 'logic/**'
      - '.github/workflows/**'
      - 'ci/**'

# TODO: is this even used anywhere?
env:
  GREENMO_AWS_REGION: ${{ vars.GREENMO_AWS_REGION }}
  GREENMO_AWS_ACCOUNT: ${{ vars.GREENMO_AWS_ACCOUNT }}

jobs:
  dagger:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dagger CLI
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh
        working-directory: /usr/local
      - name: Install CI dependencies
        run: npm ci
        working-directory: ci
      - name: Run Dagger
        run: npm run dagger
        working-directory: ci
        env:
          GREENMO_API_KEY: ${{ secrets.GREENMO_API_KEY }}
          GREENMO_AWS_ACCESS_KEY_ID: ${{ secrets.GREENMO_AWS_ACCESS_KEY_ID }}
          GREENMO_AWS_SECRET_ACCESS_KEY: ${{ secrets.GREENMO_AWS_SECRET_ACCESS_KEY }}
          GREENMO_OPEN_MAPS_API_TOKEN: ${{ secrets.GREENMO_OPEN_MAPS_API_TOKEN }}
