name: GreenMo Stalker deployment

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  AWS_REGION: "eu-central-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
        working-directory: cdk
      - run: npm i
        working-directory: cdk/lambda/chargableCars
      # - run: npm test
      #   working-directory: cdk
      - run: npx cdk deploy
        working-directory: cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          OPEN_MAPS_API_TOKEN: ${{ vars.OPEN_MAPS_API_TOKEN }}
          CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}
