name: GreenMo Stalker deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'cdk/**'
      - 'logic/**'
      - '.github/workflows/**'
      - 'ci/**'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}

jobs:
  dagger:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: curl -L https://dl.dagger.io/dagger/install.sh | sh
        name: Install Dagger CLI
        working-directory: /usr/local
      - run: npm i
        name: install
        working-directory: ci
      - run: npm run dagger
        name: dagger
        working-directory: ci
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPEN_MAPS_API_TOKEN: ${{ secrets.OPEN_MAPS_API_TOKEN }}
